/*
 Wheel diameter = Nominal diameter is often used. That's the approximate diameter in inches: 27in for a 700C wheel. Cycle uses the measured diameter, including the tyre fitted.
 */

DROP TABLE IF EXISTS public.tyres cascade;
CREATE TABLE
  public.tyres (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NULL,
    "diameter" NUMERIC NULL
  );
 
INSERT INTO
  public.tyres ("name", "diameter")
VALUES
  ('whatever', 27.5)

/*
Chainring = Toothed ring attached to the crank.
Cog = One of the teeth on a chainring or sprocket.
 */

DROP TABLE IF EXISTS public.chainrings cascade;
CREATE TABLE public.chainrings (
	id int GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NULL,
	"cogs" numeric NULL
);

INSERT INTO public.chainrings
( "name", cogs)
VALUES('front_big', 44);

INSERT INTO public.chainrings
( "name", cogs)
VALUES('front_medium', 32);

INSERT INTO public.chainrings
( "name", cogs)
VALUES('front_small', 22);

/*Sprocket = Toothed ring attached to rear wheel.*/

DROP TABLE IF EXISTS public.sprockets cascade;
CREATE TABLE public.sprockets (
	id int GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NULL,
	"cogs" numeric NULL
);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('first', 36);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('second', 32);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('third', 28);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('fourth', 24);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('fifth', 21);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('sixth', 18);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('seventh', 15);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('eight', 13);

INSERT INTO public.sprockets
( "name", cogs)
VALUES('nineth', 11);